import { readFileSync } from "fs";
import { extname, resolve, dirname } from "path";
import { createRequire } from "module";
import type { Plugin } from "rollup";
//import { compress } from "brotli-unicode";
import pkg from "brotli-unicode";
const { compress } = pkg;

const WASM_URL_PATTERN_STR = `new URL\\(['"]([^'"]+\\.wasm)['"]\\s*,\\s*import\\.meta\\.url\\)`;
const WASM_IMPORT_PATTERN_STR = `import\\s+(\\w+)\\s+from\\s+['"]([^'"]+\\.wasm)['"]\\s*;?`;

function getWasmUrlPattern(): RegExp {
  return new RegExp(WASM_URL_PATTERN_STR, "g");
}

function getWasmImportPattern(): RegExp {
  return new RegExp(WASM_IMPORT_PATTERN_STR, "g");
}

function isNodeModulePath(source: string): boolean {
  if (source.startsWith("./") || source.startsWith("../") || source.startsWith("/")) {
    return false;
  }
  return source.includes("/");
}

function resolveNodeModulePath(source: string, importer?: string): string | null {
  try {
    const require = createRequire(importer ?? import.meta.url);
    return require.resolve(source);
  } catch {
    return null;
  }
}

export default async function inlineWasm(): Promise<Plugin> {
  return {
    name: "inline-wasm",

    async resolveId(source, importer) {
      if (extname(source) !== ".wasm") return null;

      if (isNodeModulePath(source)) {
        const resolved = resolveNodeModulePath(source, importer);
        if (resolved) return resolved;
        return null;
      }

      if (importer) {
        return resolve(dirname(importer), source);
      }

      return resolve(source);
    },

    async load(id) {
      if (extname(id) !== ".wasm") return null;

      const wasmBuffer = readFileSync(id);
      const compressed = await compress(new Uint8Array(wasmBuffer));

      return buildWasmModule(compressed, id);
    },

    async transform(code, id) {
      if (extname(id) === ".wasm") return null;

      const urlMatches = Array.from(code.matchAll(getWasmUrlPattern()));
      const importMatches = Array.from(code.matchAll(getWasmImportPattern()));

      if (urlMatches.length === 0 && importMatches.length === 0) return null;

      let transformedCode = code;
      const wasmImports: string[] = [];

      for (const match of urlMatches) {
        const [fullMatch, wasmPath] = match;

        let absoluteWasmPath: string;
        if (isNodeModulePath(wasmPath)) {
          absoluteWasmPath = resolveNodeModulePath(wasmPath, id) ?? resolve(dirname(id), wasmPath);
        } else {
          absoluteWasmPath = resolve(dirname(id), wasmPath);
        }

        const importName = `__wasm_${wasmImports.length}`;
        wasmImports.push(`import { getWasmBytes as ${importName} } from '${absoluteWasmPath}';`);

        transformedCode = transformedCode.replace(fullMatch, `await ${importName}()`);
      }

      for (const match of importMatches) {
        const [fullMatch, bindingName, wasmPath] = match;

        let absoluteWasmPath: string;
        if (isNodeModulePath(wasmPath)) {
          absoluteWasmPath = resolveNodeModulePath(wasmPath, id) ?? resolve(dirname(id), wasmPath);
        } else {
          absoluteWasmPath = resolve(dirname(id), wasmPath);
        }

        const importName = `__wasm_${wasmImports.length}`;
        wasmImports.push(`import { getWasmBytes as ${importName} } from '${absoluteWasmPath}';`);

        transformedCode = transformedCode.replace(fullMatch, `const ${bindingName} = await ${importName}();`);
      }

      transformedCode = wasmImports.join("\n") + "\n" + transformedCode;

      return {
        code: transformedCode,
        map: { mappings: "" }
      };
    }
  };
}

function buildWasmModule(str: string, sourceId: string): string {
  return `
// Auto-generated by rollup-plugin-inline-wasm
// Source: ${sourceId}

import { decompress } from 'brotli-unicode/js';

const wasmStr = ${JSON.stringify(str)};

let cachedBytes = null;

function getOrDecompress() {
  if (!cachedBytes) {
    cachedBytes = decompress(wasmStr);
  }
  return cachedBytes;
}

export async function getWasmBytes() {
  return getOrDecompress();
}

export async function loadWasm(imports = {}) {
  const bytes = await getOrDecompress();
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  return instance;
}

export default loadWasm;
`.trim();
}
